#!/bin/bash
set -e

MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-""}
MYSQL_DATABASE=${MYSQL_DATABASE:-""}
MYSQL_USER=${MYSQL_USER:-""}
MYSQL_PASSWORD=${MYSQL_PASSWORD:-""}
MYSQLD_ARGS=${MYSQLD_ARGS:-""}


chown -R mysql:mysql /var/lib/mysql

if [[ ! -d /var/lib/mysql/mysql ]]; then
  echo "=> An empty or uninitialized MySQL volume is detected in /var/lib/mysql"
  echo "=> Installing MySQL DB ..."
  mysql_install_db --user mysql > /dev/null

  echo "=> Done!"  

  tfile=`mktemp`
  if [[ ! -f "$tfile" ]]; then
      return 1
  fi

  echo "=> Creating SQL to set root user"
cat << EOF > $tfile
USE mysql;
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
UPDATE user SET password=PASSWORD("$MYSQL_ROOT_PASSWORD") WHERE user='root';
EOF

  if [[ $MYSQL_DATABASE != "" ]]; then
      echo "=> Adding SQL to create DB"
      echo "CREATE DATABASE IF NOT EXISTS \`$MYSQL_DATABASE\` CHARACTER SET utf8 COLLATE utf8_general_ci;" >> $tfile

      if [[ $MYSQL_USER != "" ]]; then
          echo "=> Adding SQL to create user for DB"
          echo "GRANT ALL ON \`$MYSQL_DATABASE\`.* to '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';" >> $tfile
      fi
  fi

  echo "==> Bootstrapping MariaDB"
  /usr/sbin/mysqld --bootstrap --verbose=0 $MYSQLD_ARGS < $tfile
  rm -f $tfile

else
    echo "=> Using an existing volume of MySQL"
fi

if [[ $REMOVE_ARIA_LOG_CONTROL == "TRUE" ]]; then
  echo "=> Removing aria_log_control"
  rm -f /var/lib/mysql/aria_log_control
fi


echo "==> Starting MariaDB"
exec /usr/sbin/mysqld $MYSQLD_ARGS
